### PR TITLE
new FW container types

### PR DESCRIPTION
**Pull request by jstucke**
- added new FW container types
  - Instar BNEG
  - Tenvis PK2
  - Alphanetworks FW update script
  - Xiaomi HDR

### CODE REVIEW

**Comment by maringuu** [comment]
I guess the answer is _no_ but is there any documentation on these formats?
Or maybe a list of devices that use them?
Googling any of the new formats does not yield any useful information.

**Comment by jstucke** [comment]
> I guess the answer is _no_ but is there any documentation on these formats? Or maybe a list of devices that use them? Googling any of the new formats does not yield any useful information.

You can find several samples of PK2 here: http://apps.tenvis.com/Download/
and HDR1/2  samples can be found here: https://miuirom.org/miwifi
BNEG samples are here: https://wiki.instar.com/de/Downloadbereich/
and finally Alphanetwork samples can be found here (rebranded as D-Link): http://legacyfiles.us.dlink.com/

**Comment by jstucke** [comment]
Links to PRs for new extractor plugins:
- alphanetworks: https://github.com/fkie-cad/fact_extractor/pull/146
- PK2: https://github.com/fkie-cad/fact_extractor/pull/148
- BNEG: ToDo
- HDR1/2: ToDo

**Comment by maringuu** [comment]
Landed in 72000e4d555869ac499677e16d80e16c32a2e225

**Pull request closed without merging**
